name: 🚀 Publish to npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: 
          - $(ls packages)

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: |
          if [ ! -f ./packages/${{ matrix.package }}/package-lock.json ]; then
            npm install --package-lock-only
          fi
          npm install
        working-directory: ./packages/${{ matrix.package }}

      - name: 🔨 Build Package
        run: npm run build
        working-directory: ./packages/${{ matrix.package }}
      
      - name: 🚀 Publish to npm
        run: npm publish --access public --tag latest
        working-directory: ./packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}